project:
  type: website
  # pre-render: _scripts/run_apsimx.R
  render:
    - "*.qmd"
    - "*.md"
filters:
  - _filters/link-style.lua
  - _filters/hierarchical-title.lua

bibliography: references.bib
execute:
  echo: false
  message: false
  warning: false
  fig.align: center
  out.width: 100%
  freeze: auto
website:
  cookie-consent: true
  title: "APSIM NG Notes"
  favicon: images/icons/icon_192.png
  google-analytics: 
    tracking-id: "G-5K7WTC1T5R"
    storage: "cookies"
  site-url: https://apsimng-notes.bangyou.me
  repo-url: "https://github.com/byzheng/apsimng-notes"
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    contents: docs
  navbar:
    logo: images/icons/icon.png
    logo-alt: "APSIM Next Generation Icon"
    left:
      - href: index.qmd
        text: Home
      - href: docs/index.qmd
        text: Docs
      - href: tips/index.qmd
        text: Tips
      - about.qmd
      - disclaimer.qmd
    right:
      - icon: github
        href: https://github.com/byzheng/apsimng-notes
  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "Disclaimer"
        href: disclaimer.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 2
    filters:
      - custom-callout


custom-callout:
  needs-improvement:
    title: "üöß Needs Improvement"
    icon-symbol: "‚ö†Ô∏è"
    color: "#FFCC00"
    appearance: "default"
    collapse: false

